### PR TITLE
Structured rows

### PR DESCRIPTION
**Pull request by BertvanderVeen**
Adds an option in the `gllvm()` function to specify structured row-effect using an index vector: `row.struc`. Though probably not useful in the context of modeling species composition, it will allow to account for a certain amount of pseudo-replication in the sites, as it common in studies in community ecology.

With fixed row-effects only sets the first parameter to zero for identifiability, if `row.struc=1:n` (which is the default).

See also https://github.com/JenniNiku/gllvm/issues/16 and https://github.com/JenniNiku/gllvm/issues/1

### CODE REVIEW

**Comment by BertvanderVeen** [comment]
Note to self, to do: VA variances need to follow the same row-structure too. This is a bit more difficult as they are not part of the same matrix as the LV variances.

**Comment by JenniNiku** [comment]
Hi! Is this structure in case of fixed row params only?

**Comment by BertvanderVeen** [comment]
No! It works for random intercepts with the same index vector, I tried to make it as general as possible. The only thing I haven't done yet, is make sure the random intercept VA variances follow the same structure (see message above). I'm not sure if it's  straight forward to do due to the recent changes, and because I'm not convinced (yet) it matters.

**Comment by JenniNiku** [comment]
Ok. I have a couple of questions. This makes me wonder if right parameters goes where they should be when you changed lvs<-(matrix(param[ui],n,nlvr)) to lvs<-(matrix(param[ui],n,num_lv)), and if row params and lvs are correlated, u also includes row params: if(dependent.row) u<-cbind(r0,u)

Also if row.eff = FALSE, doesn't this cause  problem: matrix <Type> unew(n,num_lv+1); and then unew = u, when u has different dimension (n x num_lv)?

And yes I don't think that variational covariance matrices in A are correct at the moment if random row effects are structured. As we have multiple variances for row effects, so that need to be fixed I think. And then the getPredictErr function must be fixed as well.

Also, I have been playing with a little bit different structure for the rows, and lvs as well. We have worked with a data where there are two different time points for sites and we got an idea from glmm:s for longitudinal data. So what I have been playing with is eg. obs y_ijt, i=1,...,n, j=1,...,m and t=1,...,T, and then data in matrix with rows i,t and columns by j as usual. Then a model with g(mu_ijt) = beta_0j+beta_j*x_it + u_i0 + u_i'gamma_j, and u_i0 is here the row param. This could basicly work for any structure if design matrix for (u_i0, u_i) is given. But I used the same struct for random rows and lvs and this is not always what wanted so something more flexible need to be done, I think.

**Comment by JenniNiku** [comment]
With the variational covariance issue, for diagonal variational covariance structure it is easy to fix, but I'm not sure how to do that if unstructured. I guess the cov(r0,u) must be block diagonal then.

**Comment by BertvanderVeen** [comment]
Yes! By no means does this has to be a finished proposal and if you'd like something more involved we can fine-tune it  from here. 

With respect to point 1): No, I think this should work fine as for the moment, the structure for random row-effects and `dependent.row = TRUE` is the same as before. The only difference is that r0,u gets added to unew in the C++ script, based on the provided row structure, rather than in R, and the script continues with unew (which has then replicates of the r0 coefficients where necessary). When there was no random row-effect before I had the impression u was already of dimension [n,num.lv] so then nothing has changed as in that scenario r0 also doesn't get added to unew in the C++ script now, but u does. That means, regardless of the row-structure or the random-row effect the same code as before is used, does that sound sensible? If the row-effect is fixed r0 is also not added to u, but instead multiplied by xr as before (though in a loop if all(row.struc!=(1:n)) as we can't do a matrix multiplication due to the difference in length for the moment, could be addressed by changing xr based on row.struc).

With respect to point 2): the most pragmatic for the moment would be to throw an error when `all(row.struc != 1:n)`, though another solution is necessary for that in the long-term. It would have been easier if the VA variances for the random intercepts were still in their own vector like before, i.e. lg_Ar, and the covariance with the latent variables separate again in a different vector (not sure if that is the case or not at the moment, had trouble following this in the code), so that they may be structured in the same way as the VA means. However, that would require re-writing quite a bit of your new code and I wasn't ready to do that quite yet due, as I said I had trouble following where the variance and covariance terms were going and didn't want to break that.

With respect to 3):  not quite sure I follow, but if I understand correctly here, but I get the impression you would like to take this further than just a basic structure on the row-effects like now, i.e. having two row-level intercepts? That would require addressing the identifiability issue that comes with that if I'm not mistaken, i.e. setting the first entry of the nested intercept to 0 for the time points within each site?

**Comment by BertvanderVeen** [comment]
Side-question: I'd be interested in knowing how you derived the VA expectations for the random-intercepts a bit more. It seems like you came to the same solution for all the distributions, and I've treated that as the same in the quadratic GLLVM for now (as they're assumed independent of the LVs without `dependent.row=T`), but I'd like to be sure.

**Comment by JenniNiku** [comment]
Ok, maybe I have missed something in the changes, but I'm still trying to understand, eg. if dependent.row=TRUE the code puts 
if(dependent.row) u<-cbind(r0,u) #line 445 gllvm.TMB in R, so eg. for num.lv=2, nlvr =num.lv+1=3 and cbind(r0,u) is now  n x (num.lv+1)=nx3. 
Then, when we have estimates for u (nx3), that is, ui <- names(param)=="u" #(line 492) is a length of nx3
and lvs<-(matrix(param[ui],n,num_lv)) #line 495 also num_lv is used in cpp and num.lv in R
So this puts r0:s and (u_11, ..., u_n1) to lvs and so (u_12, ..., u_n2) are missing. In case of random rows the actual r0s in param[names(param)=="r0"] in the code was not used or estimated as xr was full of zeros.
Or did I miss some changes that make this work?

The reason for combining Ar and A was because we wanted to allow r0 to be correlated with u_1 and u_2, and in this case also variational covariances must be allowed to be unstructured. But obviously it now makes things harder if structured differently to the lvs. 
Maybe this should be thought through where to go with this. If more flexibility is the way to go (and I think it might be, at some point even using formula, maybe), I guess the only way is to add Ar back to the code and use that if structure is different and only A if the structure is the same for r0 and u. Other ideas?

To the last thing, not sure if I understood your question correctly. So basicly if row.eff = "random" and d=num.lv, we set u_i*=(r0_i, u_i) and gamma_j*=(1,gamma_j) and u_i*~N(0, C_sigma ) , where C_sigma = bdiag(sigma^2, I_d), and variational distribution is q(u_i*) = N_(d+1)(a_i, A_i). Then it goes pretty similarly with the VA without row effect, just the C_sigma need to be addressed in calculations, and then the approximation has sum_over (i=1,..,n){logdetA_i - tr(C_sigma^(-1)A_i) - a_iC_sigma^(-1)a_i - logdetC_sigma}.

**Comment by BertvanderVeen** [comment]
Thanks for that, I don't think you missed something, my rstudio git glitched out and didn't accept one or two commits it seems. You're right, line 445 and 452 should be commented out, which I thought I did, but apparently that didn't come through. I've addressed this now (though in practice there shouldn't be much difference).

I wasn't doubting that my code needed to be double checked, since it's been a very long week with the conference, so thanks for that again. Please let me know if you have more questions, considerations or doubts, I would like to make this work correctly (and to your satisfaction) before you consider accepting this pull request. The idea is, that u is being passed as a [n,num.lv] sized matrix, and r0 as it's own matrix (like before), after which they are combined in the C++ script using row.struc to replicate r0 to length n. 

You're completely right in saying that r0 wasn't really being estimated now, but you didn't change the code with respect to them much in the last update (it seems) so it was straight forward to put them back into place. I did notice that I neglected to add random=c("u","r0") for the laplace approximation, which I amended now.

I did experiment with putting Ar back into the code yesterday, but I didn't do that as when dependent.row=F, there are no covariances in A for the random rows (only variances), if I'm not mistaken, and the result should be the same (if we structure the variances). Hence, then it should only be necessary to prevent the combination of `all(row.struc != 1:n) `and `dependent.row=T `by adding a ` stop("You should not do this.") ` type error. Or am I wrong here? I guess the real question is if it makes sense to have a row structure with `dependent.row=TRUE` in the first place, which you are probably more equipped to answer than me. I do think, given the way I've set up row.structure, it should be straight forward to extend to multiple intercepts in the future (especially with r0 being its own matrix, that makes imposing a structure on multiple site-intercepts for identifiability more straightforward).

W.r.t. the last point, I wasn't even aiming at the correlation term yet, my main point was: given that there are different link functions, I've been surprised that the expectation over the conditional means of the distributions i.e.  int b(eta) dz, seems to have the same solution for e.g. the bernoulli and the poisson distributions, as this isn't the case for the latent variables. I'm not questioning if the way you've done that is correct, but I haven't gone through the maths and wondered if that understanding is correct. Apologies that explanation isn't clear!

**Comment by JenniNiku** [comment]
Ok, sounds good!

Yeah, it might seem to be a bit surprising. I would recommend to go through the maths as they are explained very well in the appendix of Variational Approximations for Generalized Linear Latent Variable Models by Hui, Warton, Ormerod, Haapaniemi, and Taskinen for NB (with poisson-gamma parametrization), bernoulli probit and ordinal models, if you have not done that yet. Everything else goes pretty similarly compared to these. Even if links are different, eg. for the E_q(b(eta)), there are always such things like exp(eta) popping out somewhere which makes the term 1/2*gamma_j A_i gamma_j in somewhere.

**Comment by BertvanderVeen** [comment]
Ok. So how should we continue from here? Would it be useful to lay out a small road map on how to develop this further?

I've looked at the appendix of the VA paper a lot, and agree it's very clear, so I've tried to write the appendix for the quadratic GLLVM similarly for that reason. I suspected as much for the random rows as what you write above, I should probably double check I did this OK for the quadratic GLLVM. Thanks for the clarification!

**Comment by BertvanderVeen** [comment]
OK, I went ahead and started this to see if it can work. It's definitely not finished (requires a lot of fine-tuning, testing and finishing) but I think it's the direction you would like to see it headed in?
My main reason for already attempting this is so you can have a look and see if we are on the same page. It would be good to consider if the covariance structure for Cu can be adjusted to facilitate multiple random row-effects (I'll leave that up to you, if you would like to incorporate that because the covariance structure gives me a headache and I don't have the time to consider it at the moment, sorry). For now I've worked with lg_Ar, a stop error when dependent.row = TRUE & !is.null(Xrow), and a separate flag for dependent.row = TRUE in C++.

So, for sure things that still need to be considered:
- Covariance structure for A if this feature should be combined with dependent.row = TRUE
- Properly adjusting the formula coming from row.formula
- Make sure that columns in Xrow have unique factor levels before map for makeADFun (this is a must!).
 - I made use of the levels in Xrow per column at the moment to re-arrange VA variances in between diag.iter. However, that requires all factor levels to start at 1, which is not possible given the requirement of them being unique across covariates (one way to do this is to make sure the factors of Xrow start at 1, but changing this while creating map for makeADFun).
- Haven't looked at all at properly extracting standard errors
- Identifiability structures for nested fixed row-effects
- More?

I might have time to return to this later in the week to continue.

**Comment by BertvanderVeen** [comment]
OK this is getting a bit more in shape now. It still requires another look at the C++ script, as the random row-effects remain very small, I suspect I have overlooked something.

**Comment by BertvanderVeen** [comment]
Closing this as it needs a lot more work, which I don't currently have time for, and needs to be re-worked due to the quadratic model implementation.

**Pull request closed without merging**
