### PR TITLE
Bugfixes, nlm optimizer, and allFit

### PR DESCRIPTION
**Pull request by BertvanderVeen**
- Improved starting values for reduced rank regression (still running simulations so might tweak later)
- Fixed bug in plotting

### CODE REVIEW

**Comment by BertvanderVeen** [comment]
I've added an optimizer to the R-package "nlm" from base R, and written a simple function that re-fits a GLLVM model object with all three optimizers and starting values "zero", "random", "res", "res" and "n.init = 3", so that users can more simply find the best fitting model.

**Comment by BertvanderVeen** [comment]
Though I haven't extensively tested this, `nlm` seems more robust to poor starting values than `optim` in some cases (specifically, I have observed one case where `optim` couldn't start from the initial values at all with Bernoulli responses, whereas `nlm` could, but also the other way around). Additionally, for the same set of starting values, `nlm` occasionally provides a (slightly) better fit than both `optim` and `nlminb`.

I have now added the Niku et al. 2019 reference to the `allFit` documentation, as the function essentially implements the four recommended sets of starting values (though without jitter for "res").

**Comment by JenniNiku** [comment]
Hi, I'm going to do this week a CRAN update for the package but I probably don't have enough time to review and test the new feature "allfit" yet. So is it possible to separate the bug fixes to their own pull request so I can include them to the CRAN update?

**Comment by JenniNiku** [comment]
I tried to find if I can just merge the bug fixes but didn't find such button here.

**Comment by BertvanderVeen** [comment]
No problem, I'll have a look later.

**Comment by BertvanderVeen** [comment]
Closing this, see PR #46 instead.

**Pull request closed without merging**
