### PR TITLE
Update

### PR DESCRIPTION
**Pull request by BertvanderVeen**
(edited) This started as an update to deal with the high memory requirements of the C++ compilation, by separating the VA and LA parts into two C++ files. However, that leads to problems (see messages below), so this update remains with the existing 1 C++ file structure. In the process, I have cleaned up the C++ file and made changes, which is what this PR now represents.

Further:
- Added example for the se.gllvm function
- fixed a bug in the random slopes model for constrained and concurrent ordination
- Improved computational stability for the random slopes model
- fixed a bug in the quadratic model with Pois/NB/Gamma distributions
- Greatly improved computational stability for the quadratic model with aforementioned distributions
- Bugfix in starting values for constrained and concurrent quadratic model

### CODE REVIEW

**Comment by BertvanderVeen** [comment]
Needs a little more work.

**Comment by BertvanderVeen** [comment]
- bugfix for n.init
- unstructured VA covariance matrix for quadratic model + row intercepts now allowed

**Comment by BertvanderVeen** [comment]
There is a slight problem with this branch: I seem to have triggered CppAD's forward mode differentiation, so that various functions are throwing errors when trying to use them for getting the Hessian. So as of yet, this branch cannot be used..

**Comment by BertvanderVeen** [comment]
OK, the two-file version did not work, it threw errors along the lines of "pnorm1" order not found. This should now be back the the "old" 1-file version, but with my code improvements. Please thoroughly check against the original gllvm.cpp. If we have some memory on compilation to spare, it would be nice to declare D and Sigmab_lv as diagonal matrices.

**Comment by JenniNiku** [comment]
Do you think I can merge this now, or are you working on this?

**Comment by BertvanderVeen** [comment]
I am not working on it, so it is OK to merge.

**Pull request merged**
